on: 
    push:
     branches: 
           - master 
 
 
 
 
jobs:
    build:
        runs-on: ubuntu-latest
     
 
        steps:
           - uses: actions/checkout@v3  
 
 
           - name: "login"
             run: docker login --username  ${{ secrets.DOCER_USERNAME }} --password   ${{ secrets.DOCKER_TOKEN }}  
             
           - name: "Bulding docker image"
             run: docker build -t ${{ secrets.DOCER_USERNAME }}/mytask .
            
           - name: "Pushing to Docker hub"
             run: docker push  ${{ secrets.DOCER_USERNAME }}/mytask 



